/**
 * sync-abis.js - Sincroniza ABIs de contratos compilados al frontend
 * 
 * Uso:
 *   node scripts/sync-abis.js          # Sincroniza todos los ABIs
 *   node scripts/sync-abis.js Auction  # Sincroniza solo Auction
 * 
 * Se ejecuta automáticamente después de compilar con:
 *   npm run compile:sync
 */

const fs = require('fs');
const path = require('path');

// Configuración
const CONFIG = {
  // Carpeta de artifacts de Hardhat
  artifactsDir: path.join(__dirname, '..', 'artifacts', 'src'),
  
  // Destino en frontend
  frontendAbiDir: path.join(__dirname, '..', '..', 'frontend', 'src', 'contracts'),
  
  // Contratos a sincronizar (nombre del archivo .sol sin extensión)
  contracts: ['Auction', 'Marketplace'],
  
  // También generar un archivo de direcciones (se actualiza en deploy)
  addressesFile: 'addresses.json'
};

// Colores para consola
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
  dim: '\x1b[2m'
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function ensureDirectoryExists(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
    log(`📁 Creada carpeta: ${dirPath}`, 'cyan');
  }
}

function extractAbi(contractName) {
  const artifactPath = path.join(
    CONFIG.artifactsDir,
    `${contractName}.sol`,
    `${contractName}.json`
  );
  
  if (!fs.existsSync(artifactPath)) {
    log(`⚠️  No encontrado: ${artifactPath}`, 'yellow');
    log(`   ¿Compilaste primero? Ejecuta: npm run compile`, 'dim');
    return null;
  }
  
  try {
    const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
    return {
      abi: artifact.abi,
      bytecode: artifact.bytecode,
      contractName: artifact.contractName,
      sourceName: artifact.sourceName
    };
  } catch (error) {
    log(`❌ Error leyendo ${contractName}: ${error.message}`, 'red');
    return null;
  }
}

function saveAbi(contractName, data) {
  ensureDirectoryExists(CONFIG.frontendAbiDir);
  
  const outputPath = path.join(CONFIG.frontendAbiDir, `${contractName}ABI.json`);
  
  // Guardar solo el ABI (más liviano para frontend)
  fs.writeFileSync(outputPath, JSON.stringify(data.abi, null, 2));
  
  const stats = fs.statSync(outputPath);
  const sizeKb = (stats.size / 1024).toFixed(2);
  
  log(`✅ ${contractName}ABI.json (${sizeKb} KB)`, 'green');
  return outputPath;
}

function createTypesFile(contracts) {
  // Crear archivo TypeScript con tipos para los contratos
  const typesContent = `// Auto-generated by sync-abis.js - DO NOT EDIT
// Generated at: ${new Date().toISOString()}

${contracts.map(c => `import ${c}ABI from './${c}ABI.json';`).join('\n')}

export const CONTRACTS = {
${contracts.map(c => `  ${c}: { abi: ${c}ABI, name: '${c}' },`).join('\n')}
} as const;

export type ContractName = keyof typeof CONTRACTS;

// Re-export ABIs
${contracts.map(c => `export { default as ${c}ABI } from './${c}ABI.json';`).join('\n')}
`;

  const typesPath = path.join(CONFIG.frontendAbiDir, 'index.ts');
  fs.writeFileSync(typesPath, typesContent);
  log(`✅ index.ts (exports)`, 'green');
}

function createAddressesTemplate() {
  const addressesPath = path.join(CONFIG.frontendAbiDir, CONFIG.addressesFile);
  
  if (!fs.existsSync(addressesPath)) {
    const template = {
      _comment: 'Actualizado automáticamente por el script de deploy',
      _lastUpdate: null,
      networks: {
        localhost: {
          chainId: 31337,
          Auction: '',
          Marketplace: ''
        },
        sepolia: {
          chainId: 11155111,
          Auction: '',
          Marketplace: ''
        },
        mainnet: {
          chainId: 1,
          Auction: '',
          Marketplace: ''
        }
      }
    };
    
    fs.writeFileSync(addressesPath, JSON.stringify(template, null, 2));
    log(`✅ ${CONFIG.addressesFile} (template)`, 'green');
  }
}

function syncAbis(specificContract = null) {
  log('\n🔄 Sincronizando ABIs de contratos...\n', 'cyan');
  
  const contractsToSync = specificContract 
    ? [specificContract]
    : CONFIG.contracts;
  
  const synced = [];
  
  for (const contractName of contractsToSync) {
    const data = extractAbi(contractName);
    if (data) {
      saveAbi(contractName, data);
      synced.push(contractName);
    }
  }
  
  if (synced.length > 0) {
    createTypesFile(CONFIG.contracts);
    createAddressesTemplate();
    
    log(`\n✨ Sincronizados ${synced.length} contratos`, 'green');
    log(`📂 Destino: ${CONFIG.frontendAbiDir}`, 'dim');
  } else {
    log('\n⚠️  No se sincronizó ningún contrato', 'yellow');
  }
  
  return synced;
}

// Ejecutar si es llamado directamente
if (require.main === module) {
  const specificContract = process.argv[2];
  syncAbis(specificContract);
}

module.exports = { syncAbis, CONFIG };
