// Auto-generated by sync-abis.js - DO NOT EDIT
// Generated at: 2026-01-02T21:29:31.751Z

import AuctionABI from './AuctionABI.json';
import MarketplaceABI from './MarketplaceABI.json';

export const CONTRACTS = {
  Auction: { abi: AuctionABI, name: 'Auction' },
  Marketplace: { abi: MarketplaceABI, name: 'Marketplace' },
} as const;

export type ContractName = keyof typeof CONTRACTS;

// Re-export ABIs
export { default as AuctionABI } from './AuctionABI.json';
export { default as MarketplaceABI } from './MarketplaceABI.json';
